COLUMNS:
  pclass : int64
  nom : str
  sexe : str
  age : int64
  cabin_num : int64
  free sulfur dioxide : float64
  total sulfur dioxide : float64
  density : float64
  pH : float64
  sulphates : float64
  alcohol : float64
  quality : int64


TARGET_COLUMN:
  name: quality
